### PR TITLE
added bash links

### PR DESCRIPTION
**Pull request by xeon-zolt**
bash is a must know thing according to me

### CODE REVIEW

**Comment by mattjegan** [comment]
Thanks @xeon-zolt

**Comment by xeon-zolt** [comment]
i have links for other stuff so should i add the alternate links or replace them ?

**Comment by mattjegan** [comment]
I've already merged this change in so any new stuff would be awesome on a new pull request. Thanks :smile:

**Comment by xeon-zolt** [comment]
no i mean like for html you have w3school but i think it is good as reference websitew but to learn html i find www.codecademy.com better

**Pull request merged**
